name: Check Lint With Stylua
on:
  pull_request:
    paths:
      - "**.lua"
permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write
jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: .
      - name: suggester
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: stylua
          fail_on_error: true
